language: csharp
python:
  - "2.7"
  - "3.4"
solution: AntlrGrammarEditor.sln
before_install:
    - sudo apt-get install nunit-console
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip2 install antlr4-python2-runtime
    - sudo pip3 install antlr4-python3-runtime
    - sudo $(which npm) install antlr4
    - export GOPATH=$HOME/gopath:$GOPATH
    - go get github.com/pboyer/antlr4/runtime/Go/antlr
    - python2 -V
    - python3 -V
    - node -v
    - go version
install:
    - nuget sources add -Name Avalonia -Source https://www.myget.org/F/avalonia-ci/api/v2
    - nuget restore
    - cd AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Lexer.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Parser.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - cd ..
script:
    - xbuild /p:Configuration=Release AntlrGrammarEditor.sln /p:TargetFrameworkVersion="v4.5"
    - nunit-console ./AntlrGrammarEditor.Tests/bin/Release/AntlrGrammarEditor.Tests.dll
    