language: csharp
solution: AntlrGrammarEditor.sln
before_install:
    - sudo apt-get install nunit-console
    - sudo apt-get install python3-setuptools
    - sudo easy_install3 pip
    - sudo curl https://bootstrap.pypa.io/3.2/get-pip.py | python3.2 - --upgrade
    - sudo pip2 install antlr4-python2-runtime
    - sudo pip3 install antlr4-python3-runtime
    - sudo $(which npm) install antlr4
    - export GOPATH=$HOME/gopath:$GOPATH
    - go get github.com/pboyer/antlr4/runtime/Go/antlr
    - node -v
    - go version
install:
    - nuget sources add -Name Avalonia -Source https://www.myget.org/F/avalonia-ci/api/v2
    - nuget restore
    - cd AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Lexer.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Parser.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - cd ..
script:
    - xbuild /p:Configuration=Release AntlrGrammarEditor.sln /p:TargetFrameworkVersion="v4.5"
    - nunit-console ./AntlrGrammarEditor.Tests/bin/Release/AntlrGrammarEditor.Tests.dll
    