language: csharp
solution: AntlrGrammarEditor.sln
before_install:
    - sudo apt-get install nunit-console
    - sudo pip install antlr4-python3-runtime
    - sudo npm install antlr4
    - sudo go get github.com/pboyer/antlr4/runtime/Go/antlr
install:
    - nuget sources add -Name Avalonia -Source https://www.myget.org/F/avalonia-ci/api/v2
    - nuget restore
    - cd AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Lexer.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - java -jar "Generators/antlr-4.5.3-csharpsharwell.jar" "ANTLRv4Parser.g4" -o "Generated" -Dlanguage=CSharp_v4_5 -package AntlrGrammarEditor
    - cd ..
script:
    - xbuild /p:Configuration=Release AntlrGrammarEditor.sln /p:TargetFrameworkVersion="v4.5"
    - nunit-console ./AntlrGrammarEditor.Tests/bin/Release/AntlrGrammarEditor.Tests.dll
    