version: 1.0.{build}
configuration: Release
platform: x86
environment:
  matrix:
  - python2: C:\Python27-x64
    python3: C:\Python35-x64
    pip2: C:\Python27-x64\Scripts\pip.exe
    pip3: C:\Python35-x64\Scripts\pip.exe
    py: C:\Python35-x64\py.exe
    GOPATH: C:\GOPATH
    java: C:\Program Files\Java\jdk1.7.0\bin\java.exe
    javac: C:\Program Files\Java\jdk1.7.0\bin\javac.exe
install:
- cmd: >-
    pip2 install antlr4-python2-runtime
    pip3 install antlr4-python3-runtime
    go get github.com/antlr/antlr4/runtime/Go/antlr
    npm install antlr4
before_build:
- cmd: nuget sources add -Name Avalonia -Source https://www.myget.org/F/avalonia-ci/api/v2
build:
  project: AntlrGrammarEditor.sln
  verbosity: normal
test:
  assemblies: AntlrGrammarEditor.Tests\bin\$(configuration)\AntlrGrammarEditor.Tests.dll